import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState, type FormEvent } from "react";
import { Package, ShoppingBag, Sparkles, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { lovable } from "@/integrations/lovable/index";
import { supabase } from "@/integrations/supabase/client";
import { products, formatPrice } from "@/data/products";

type Consultation={id:string;name:string;email:string;wedding_city:string;wedding_function:string;preferred_style:string;budget_range:string;status:string;created_at:string};
export const Route=createFileRoute("/admin")({head:()=>({meta:[{title:"Private Atelier Administration — NOORAA"},{name:"description",content:"Protected NOORAA atelier administration."},{property:"og:title",content:"NOORAA Atelier Administration"},{property:"og:description",content:"Protected atelier operations."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"},{name:"robots",content:"noindex,nofollow"}]}),component:AdminPage});

function AdminPage(){const [mode,setMode]=useState<"loading"|"signedOut"|"forbidden"|"admin">("loading");const [rows,setRows]=useState<Consultation[]>([]);const [message,setMessage]=useState("");
useEffect(()=>{void (async()=>{const {data:{user}}=await supabase.auth.getUser();if(!user){setMode("signedOut");return}const {data:role}=await supabase.from("user_roles").select("role").eq("user_id",user.id).eq("role","admin").maybeSingle();if(!role){setMode("forbidden");return}const {data}=await supabase.from("bridal_consultations").select("id,name,email,wedding_city,wedding_function,preferred_style,budget_range,status,created_at").order("created_at",{ascending:false});setRows(data??[]);setMode("admin")})()},[]);
const login=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await supabase.auth.signInWithPassword({email:String(f.get("email")),password:String(f.get("password"))});if(error){setMessage(error.message);return}window.location.reload()};
const google=async()=>{sessionStorage.setItem("nooraa_auth_return","/admin");const result=await lovable.auth.signInWithOAuth("google",{redirect_uri:window.location.origin});if(result.error)setMessage(result.error.message)};
if(mode==="loading")return <div className="grid min-h-[65vh] place-items-center"><p className="editorial-kicker">OPENING THE ATELIER…</p></div>;
if(mode==="signedOut")return <div className="mx-auto flex min-h-[70vh] max-w-md items-center px-6"><form onSubmit={login} className="w-full"><p className="editorial-kicker">PRIVATE ACCESS</p><h1 className="mt-3 text-5xl">Atelier administration</h1><div className="mt-8 space-y-4"><Input name="email" type="email" placeholder="Email" required className="h-12 rounded-none"/><Input name="password" type="password" placeholder="Password" required className="h-12 rounded-none"/><Button className="h-12 w-full">SIGN IN</Button><Button type="button" onClick={google} variant="outline" className="h-12 w-full">CONTINUE WITH GOOGLE</Button>{message&&<p className="text-sm text-destructive">{message}</p>}</div></form></div>;
if(mode==="forbidden")return <div className="mx-auto max-w-xl px-6 py-28 text-center"><h1 className="text-5xl">Private atelier access</h1><p className="mt-5 text-muted-foreground">Your account is signed in, but does not have atelier administration access.</p><Button className="mt-8" onClick={async()=>{await supabase.auth.signOut();window.location.reload()}}>SIGN OUT</Button></div>;
return <div className="mx-auto max-w-[1500px] px-6 py-14"><div className="flex items-end justify-between"><div><p className="editorial-kicker">PRIVATE ATELIER</p><h1 className="mt-2 text-6xl">Administration</h1></div><Button variant="outline" onClick={async()=>{await supabase.auth.signOut();window.location.reload()}}>SIGN OUT</Button></div><div className="mt-10 grid gap-4 md:grid-cols-4">{[[Users,rows.length,"Consultations"],[ShoppingBag,0,"Orders"],[Package,products.length,"Products"],[Sparkles,products.filter(p=>p.madeToOrder).length,"Made to order"]].map(([Icon,n,label])=>{const C=Icon as typeof Users;return <div key={label as string} className="border p-5"><C/><p className="mt-5 font-display text-4xl">{n as number}</p><p className="text-xs uppercase text-muted-foreground">{label as string}</p></div>})}</div><div className="mt-12"><h2 className="text-3xl">Bridal consultations</h2><div className="mt-5 overflow-x-auto border"><table className="w-full min-w-[800px] text-left text-sm"><thead className="bg-muted"><tr>{["Bride","Function","City","Style","Budget","Status"].map(x=><th key={x} className="p-4 editorial-kicker">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-4"><b>{r.name}</b><br/><span className="text-muted-foreground">{r.email}</span></td><td className="p-4">{r.wedding_function}</td><td className="p-4">{r.wedding_city}</td><td className="p-4">{r.preferred_style}</td><td className="p-4">{r.budget_range}</td><td className="p-4 uppercase">{r.status}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-8 text-center text-muted-foreground">No consultation requests yet.</p>}</div></div><div className="mt-12"><h2 className="text-3xl">Product & inventory overview</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{products.map(p=><div key={p.id} className="flex items-center gap-4 border p-3"><img src={p.image} alt="" className="h-20 w-16 object-cover"/><div className="flex-1"><p className="font-display text-xl">{p.name}</p><p className="text-xs text-muted-foreground">{p.category} · {p.madeToOrder?"Made to order":"Available"}</p></div><p className="text-sm">{formatPrice(p.price)}</p></div>)}</div></div></div>}