import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import hero from "@/assets/nooraa-hero.jpg";
import wine from "@/assets/nooraa-wine.jpg";
import sage from "@/assets/nooraa-sage.jpg";
import craft from "@/assets/nooraa-craft.jpg";
import { Button } from "@/components/ui/button";
import { ProductCard } from "@/components/nooraa/product-card";
import { StyleQuiz } from "@/components/nooraa/style-quiz";
import { ConsultationForm } from "@/components/nooraa/consultation-form";
import { products } from "@/data/products";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [{ title: "NOORAA — Indian Bridal Couture" }, { name: "description", content: "Private Indian bridal couture shaped by heritage craft and contemporary silhouettes." }, { property: "og:title", content: "NOORAA — The Bridal Edit" }, { property: "og:description", content: "Where heritage becomes yours." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: HomePage,
});

const ceremonies = [["Wedding",hero],["Mehendi",sage],["Reception",wine]];
const personalities = ["The Traditionalist","The Modernist","The Romantic","The Minimalist","The Maximalist"];

function HomePage() { return <>
  <section className="relative min-h-[calc(100vh-7rem)] overflow-hidden">
    <img src={hero} alt="NOORAA ivory bridal lehenga" width={1536} height={1920} className="absolute inset-0 h-full w-full object-cover object-[center_26%]" />
    <div className="absolute inset-0 bg-foreground/25" />
    <div className="relative flex min-h-[calc(100vh-7rem)] items-end px-6 pb-16 text-primary-foreground md:px-14 md:pb-20"><div className="max-w-3xl reveal-soft"><p className="editorial-kicker">THE BRIDAL EDIT</p><h1 className="mt-3 text-5xl font-normal leading-none sm:text-7xl md:text-8xl">Where heritage<br/>becomes yours.</h1><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="h-13 bg-background text-foreground hover:bg-secondary"><Link to="/shop">EXPLORE THE COLLECTION</Link></Button><Button asChild size="lg" variant="outline" className="h-13 border-background bg-background/10 text-primary-foreground hover:bg-background hover:text-foreground"><Link to="/consultation">BOOK A BRIDAL CONSULTATION</Link></Button></div></div></div>
  </section>
  <section className="mx-auto max-w-4xl px-6 py-24 text-center md:py-36"><p className="editorial-kicker text-muted-foreground">THE HOUSE OF NOORAA</p><h2 className="mt-5 text-4xl font-normal leading-tight md:text-6xl">Couture conceived as memory—shaped by the hand, held by generations.</h2><p className="mx-auto mt-7 max-w-2xl leading-8 text-muted-foreground">We bring India’s storied techniques into an exacting, contemporary wardrobe for the modern bride.</p></section>
  <section className="px-5 pb-28 md:px-10"><div className="mx-auto max-w-[1500px]"><div className="mb-10 flex items-end justify-between"><div><p className="editorial-kicker">CURATED FOR YOU</p><h2 className="mt-2 text-4xl md:text-5xl">Featured bridal collection</h2></div><Link to="/shop" className="hidden items-center gap-2 text-xs font-semibold md:flex">VIEW ALL <ArrowRight className="h-4 w-4"/></Link></div><div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0,4).map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section>
  <section className="bg-muted px-5 py-24 md:px-10"><div className="mx-auto max-w-[1500px]"><p className="editorial-kicker">SHOP BY CEREMONY</p><h2 className="mt-2 text-4xl md:text-5xl">Every ritual, considered.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{ceremonies.map(([name,img])=><Link key={name} to="/shop" search={{category:"All"}} className="group relative aspect-[3/4] overflow-hidden"><img src={img} alt={`${name} couture`} className="h-full w-full object-cover transition duration-700 group-hover:scale-[1.03]"/><div className="absolute inset-0 bg-foreground/20"/><h3 className="absolute bottom-6 left-6 text-4xl text-primary-foreground">{name}</h3></Link>)}</div></div></section>
  <section className="px-6 py-24 text-center"><p className="editorial-kicker">SHOP BY BRIDAL PERSONALITY</p><h2 className="mt-3 text-4xl md:text-5xl">Dress the woman you are.</h2><div className="mx-auto mt-10 flex max-w-5xl flex-wrap justify-center gap-x-8 gap-y-5">{personalities.map(x=><Link key={x} to="/shop" search={{category:"All"}} className="border-b border-foreground pb-1 font-display text-2xl">{x}</Link>)}</div></section>
  <section className="grid md:grid-cols-2"><img src={wine} alt="Mehrab bridal editorial" width={1200} height={1600} loading="lazy" className="h-full min-h-[620px] w-full object-cover"/><div className="flex items-center bg-primary p-10 text-primary-foreground md:p-20"><div><p className="editorial-kicker">THE MEHRAB STORY</p><h2 className="mt-5 text-5xl md:text-7xl">An heirloom, made unmistakably yours.</h2><p className="mt-6 max-w-xl leading-8 opacity-80">Rich velvets, arched motifs and metal thread speak to a lineage of celebration—reimagined with a clean couture hand.</p><Button asChild variant="outline" className="mt-8 h-12 border-primary-foreground bg-transparent text-primary-foreground hover:bg-primary-foreground hover:text-primary"><Link to="/shop">DISCOVER MEHRAB</Link></Button></div></div></section>
  <section className="px-5 py-28 md:px-10"><div className="mx-auto grid max-w-[1400px] gap-12 md:grid-cols-[1.25fr_.75fr] md:items-center"><img src={craft} alt="Artisan creating zardozi embroidery" width={1600} height={1104} loading="lazy"/><div><p className="editorial-kicker">THE ART OF THE HAND</p><h2 className="mt-4 text-5xl">Crafted for your chapter.</h2><p className="mt-5 text-xl font-display">“Not just a wedding outfit. A piece of your story.”</p><div className="mt-8 grid grid-cols-2 gap-5 text-sm"><span>Zardozi</span><span>Resham</span><span>Gota Patti</span><span>Bandhani</span></div></div></div></section>
  <section className="bg-muted px-5 py-24 md:px-10"><div className="mx-auto max-w-[1500px]"><p className="editorial-kicker">JUST ARRIVED</p><h2 className="mt-2 text-4xl md:text-5xl">New in the atelier</h2><div className="mt-10 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{products.slice(4).map(p=><ProductCard key={p.id} product={p}/>)}</div></div></section>
  <section className="px-6 py-28"><div className="mx-auto max-w-6xl"><div className="text-center"><p className="editorial-kicker">A PRIVATE EDIT</p><h2 className="mt-3 text-5xl">Find your bridal style</h2></div><div className="mt-14"><StyleQuiz/></div></div></section>
  <section className="grid bg-secondary md:grid-cols-2"><img src={sage} alt="NOORAA private bridal consultation" loading="lazy" width={1200} height={1600} className="h-full min-h-[650px] w-full object-cover"/><div className="p-8 md:p-16"><p className="editorial-kicker">PRIVATE APPOINTMENTS</p><h2 className="mt-3 text-5xl">Your bridal consultation</h2><p className="mt-4 max-w-lg leading-7 text-muted-foreground">Meet one-to-one with a NOORAA stylist to shape your complete wedding wardrobe.</p><div className="mt-8"><ConsultationForm/></div></div></section>
  <section className="px-5 py-28 md:px-10"><div className="mx-auto max-w-[1400px]"><div className="flex justify-between"><div><p className="editorial-kicker">THE JOURNAL</p><h2 className="mt-2 text-5xl">Notes from the atelier</h2></div><Link to="/journal" className="text-xs font-semibold">READ ALL</Link></div><div className="mt-10 grid gap-10 md:grid-cols-3">{[[hero,"A New Language for the Bridal Lehenga"],[craft,"Why Handwork Becomes Heirloom"],[sage,"The Poetry of a Perfect Drape"]].map(([img,title])=><article key={title}><img src={img} alt="" loading="lazy" className="aspect-[4/3] w-full object-cover"/><p className="mt-5 editorial-kicker text-muted-foreground">JOURNAL · 6 MIN</p><h3 className="mt-2 text-3xl">{title}</h3></article>)}</div></div></section>
  <section className="border-t px-6 py-20 text-center"><p className="editorial-kicker">LETTERS FROM NOORAA</p><h2 className="mt-3 text-4xl">Private previews, atelier stories.</h2><form className="mx-auto mt-8 flex max-w-lg border-b"><input type="email" placeholder="Your email address" aria-label="Email address" className="h-12 flex-1 bg-transparent outline-none"/><Button type="submit" variant="ghost">SUBSCRIBE</Button></form></section>
  </>; }