import { createFileRoute } from "@tanstack/react-router";
import { SlidersHorizontal } from "lucide-react";
import { useMemo, useState } from "react";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Sheet, SheetContent, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { ProductCard } from "@/components/nooraa/product-card";
import { products } from "@/data/products";

export const Route = createFileRoute("/shop")({ validateSearch: z.object({category:z.string().optional().default("All")}), head:()=>({meta:[{title:"Bridal Collection — NOORAA"},{name:"description",content:"Explore NOORAA bridal lehengas, sarees, gowns, shararas, dupattas and jewellery."},{property:"og:title",content:"The Bridal Collection — NOORAA"},{property:"og:description",content:"Contemporary Indian couture, made for your chapter."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}), component: ShopPage });
const filters = {Category:["Lehengas","Sarees","Gowns","Shararas","Dupattas","Jewellery"],Occasion:["Wedding","Reception","Mehendi","Haldi","Cocktail"],Color:["Ivory","Champagne","Blush","Sage","Emerald","Burgundy","Maroon"],Price:["Under ₹1,50,000","₹1,50,000 – ₹2,50,000","Above ₹2,50,000"],Fabric:["Silk","Velvet","Organza","Tulle","Chanderi"],Embroidery:["Zardozi","Resham","Gota Patti","Kundan"],Silhouette:["Classic","Dramatic","Draped","Fluid","Column","Statement"],"Made to Order":["Yes"]};
function ShopPage(){const search=Route.useSearch();const [selected,setSelected]=useState<Record<string,string[]>>(search.category!=="All"?{Category:[search.category]}:{});const toggle=(k:string,v:string)=>setSelected(s=>({...s,[k]:s[k]?.includes(v)?s[k].filter(x=>x!==v):[...(s[k]??[]),v]}));const filtered=useMemo(()=>products.filter(p=>Object.entries(selected).every(([k,vals])=>!vals.length||vals.some(v=>k==="Category"?p.category===v:k==="Occasion"?p.occasion===v:k==="Color"?p.color===v:k==="Fabric"?p.fabric===v:k==="Embroidery"?p.embroidery===v:k==="Silhouette"?p.silhouette===v:k==="Made to Order"?p.madeToOrder:k==="Price"?(v.startsWith("Under")?p.price<150000:v.startsWith("Above")?p.price>250000:p.price>=150000&&p.price<=250000):true))),[selected]);const FilterBody=()=> <div className="space-y-7">{Object.entries(filters).map(([k,vals])=><div key={k}><p className="editorial-kicker">{k}</p><div className="mt-3 space-y-2">{vals.map(v=><label key={v} className="flex items-center gap-3 text-sm"><Checkbox checked={selected[k]?.includes(v) ?? false} onCheckedChange={()=>toggle(k,v)}/>{v}</label>)}</div></div>)}</div>;return <div className="mx-auto max-w-[1500px] px-5 py-14 md:px-10"><p className="editorial-kicker">THE COLLECTION</p><div className="mt-2 flex items-end justify-between"><h1 className="text-5xl md:text-7xl">Couture, considered.</h1><span className="text-sm text-muted-foreground">{filtered.length} pieces</span></div><div className="mt-12 grid gap-12 md:grid-cols-[220px_1fr]"><aside className="hidden md:block"><FilterBody/></aside><div><Sheet><SheetTrigger asChild><Button variant="outline" className="mb-6 w-full md:hidden"><SlidersHorizontal/> FILTER & SORT</Button></SheetTrigger><SheetContent side="bottom" className="max-h-[85vh] overflow-auto"><SheetTitle className="font-display text-3xl">Refine the collection</SheetTitle><div className="mt-8"><FilterBody/></div></SheetContent></Sheet><div className="grid gap-x-6 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(p=><ProductCard key={p.id} product={p}/>)}</div>{!filtered.length&&<p className="py-24 text-center text-muted-foreground">No pieces match this private edit.</p>}</div></div></div>}